on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  BUILD_PATH: repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: repo

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: repo/package.json
          run_install: |
            - cwd: repo

      - uses: actions/setup-node@v5
        with:
          node-version: 22.20.0
          cache: pnpm
          cache-dependency-path: repo/pnpm-lock.yaml

      - id: pages
        uses: actions/configure-pages@v5

      - working-directory: repo
        run: |
          pnpm build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
