on:
  workflow_dispatch:
  push:
    branches: [master]
  repository_dispatch:
    types: [surge-build-release]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: "22.20.0"
          cache: "pnpm"

      - id: pages
        uses: actions/configure-pages@v5

      - run: |
          pnpm install
          pnpm build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
