on:
  workflow_dispatch:
  push:
    branches: [master]
  repository_dispatch:
    types: [surge-build-release]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: repo

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: "22.20.0"
          cache: "pnpm"

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install node_modules
        run: |
          pnpm install

      - name: Astro build
        run: |
          pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
