on:
  push:
    branches:
      - master

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.WEB }}
    steps:
      - run: |
          gh api repos/${{ github.repository }}/dispatches \
            --method POST \
            --field event_type=build
