on:
  repository_dispatch:
    types: [surge-build-stable]

jobs:
  commit-payload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.WEB }}

      - run: |
          jq . <<< '${{ toJson(github.event.client_payload) }}' > src/content/generated/surge-build-stable.json
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m 'github-actions: Update surge-build-stable.json from dispatch event' || echo "No changes to commit"
          git push origin master
