on:
  repository_dispatch:
    types: [surge-build-release]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: repo

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: repo/package.json
          run_install: |
            - cwd: repo

      - uses: actions/setup-node@v5
        with:
          node-version: 22.20.0
          cache: pnpm
          cache-dependency-path: repo/pnpm-lock.yaml

      - working-directory: repo
        run: |
          pnpm generate

      - working-directory: repo
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m 'github-actions: Update generated files'
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh repo push origin master

  build:
    needs: generate
    uses: ./.github/workflows/build.yaml
